/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class Dog {

    private String breed;

    public Dog(String breed) {
        this.breed = breed;
    }

    public String getBreed() {
        return breed;
    }
}
